### ISSUE TITLE
Support netstandard2.0

### ISSUE THREAD

**Issue by Compufreak345** [GaProgMan/OwaspHeaders.Core#11]
Hi there,

although you mention to support netstandard2.0 [here](https://github.com/GaProgMan/OwaspHeaders.Core/issues/5) the project is built against netcoreapp2.0, not netstandard2.0 - I had to make 2 small changes to make it work with my .Net Core-project built against the 4.6.1 framework. You can have a look at the changes [here](https://github.com/GaProgMan/OwaspHeaders.Core/compare/master...Compufreak345:netstandard2.0?expand=1) - should I commit a pull request? I didn't test it against a full netcoreapp2.0, but it should work.

Thanks & best regards,
Christoph

**Comment by GaProgMan** [comment]
Please do submit a pull request.

I can happily test in my dev and testing environments

**Comment by GaProgMan** [comment]
Fixed with pull request #13

**Comment by Compufreak345** [comment]
Hi,

first of all - thanks for merging my PRs 😃 
I currently have to build the project manually to have it work with .Net-Standard 2.0 - it would be great if it's possible to release a new version to Nuget so I can use the Nuget-Package again. 

Thanks & best regards,
Christoph

**Comment by GaProgMan** [comment]
When I merged the pull request AppVeyor performed an auto build,. test and deploy to NuGet.

You should be able to see the build, test and deploy log [here](https://ci.appveyor.com/project/GaProgMan/owaspheaders-core/build/2.0.13).

I'll update the version number in the csproj and deploy again, that way the NuGet package version number will update correctly.

**Comment by GaProgMan** [comment]
I've pushed a version of the code to AppVeyor with a new version number.

It has been built, tested and deployed to NuGet successfully (as can be seen [here](https://ci.appveyor.com/project/GaProgMan/owaspheaders-core/build/2.0.14)), but it may take a few hours for NuGet to index it.
