### ISSUE TITLE
Remove dependency to Microsoft.AspNetCore.All

### ISSUE THREAD

**Issue by MartinJohns** [GaProgMan/OwaspHeaders.Core#28]
By adding a dependency to `Microsoft.AspNetCore.All` in version 3.3.0 you also implictly added a dependency to .NET Core 2.0. As a direct result you excluded projects targetting .NET Standard 2.0. This prevents us from upgrading to the latest version.

You should consider just adding the specific packages you require as a dependency instead of the ominous `.All` package. Most ASP.NET Core packages target .NET Standard, and not .NET Core.

**Comment by GaProgMan** [comment]
I agree completely with this.

I'll take a look through the parts of the All package which are required and reduce it down.
