### ISSUE TITLE
Feature-Policy header is not supported

### ISSUE THREAD

**Issue by GaProgMan** [GaProgMan/OwaspHeaders.Core#31]
## Description

The OwaspHeaders.Core middleware does not yet include support for [Feature-Policy](https://scotthelme.co.uk/a-new-security-header-feature-policy/) which is a header related to enabling or disabling certain JavaScript API features.

Quote from Scott Helme's blog:

> TheFeature Policy is being created to allow site owners to enable and disable certain web platform features on their own pages and those they embed. Being able to restrict the features your site can use is really nice but being able to restrict features that sites you embed can use is an even better protection to have.

Source: [A new security header: Feature Policy](https://scotthelme.co.uk/a-new-security-header-feature-policy/)

## Links to Header Information

- [A new security header: Feature Policy](https://scotthelme.co.uk/a-new-security-header-feature-policy/)
- [RFC document](https://wicg.github.io/feature-policy/)
- [Feature-Policy GitHub spec](https://github.com/WICG/feature-policy/blob/master/features.md)

**Comment by GaProgMan** [comment]
Due to an update to [Security Headers](https://securityheaders.com/) (see footnote), which is a tool that a lot of users use to check their website security headers, this header should be implemented as soon as possible.

##### Footnote

[Security Headers Updates](https://scotthelme.co.uk/security-headers-updates/#feature-policy-now-required-for-an-a-) - published July 22nd, 2019

**Comment by jamie-taylor-rjj** [comment]
Feature-Policy has been deprecated in favour of Permissions-Policy. This issue should be closed. See: https://owasp.org/www-project-secure-headers/#feature-policy for further details.
