### ISSUE TITLE
blob:, *, data: are capsulated between quotes

### ISSUE THREAD

**Issue by eL-Prova** [GaProgMan/OwaspHeaders.Core#39]
font-src, style, img etc. has the possibility for blob: or data: or *. However when creating an ContenSecurityPolicyElement the value is always capsulated with quotes but this is not valid for browsers (like Chrome) which ignores the CSP rule.

![image](https://user-images.githubusercontent.com/2064632/57930111-688d1180-78b5-11e9-99d3-007b9df13d1b.png)

![image](https://user-images.githubusercontent.com/2064632/57930200-a25e1800-78b5-11e9-82e3-c00e54f09c0a.png)

I think it will be good when setting a value, you can exclude the quotes. I will make a pull request for this.

Edit: good to show my configuration:

`new ContenSecurityPolicyElement { CommandType = CspCommandType.Directive, DirectiveOrUri = "blob:" };`

**Comment by GaProgMan** [comment]
Thank you for reporting this. I'll get on a fix right away.
