### ISSUE TITLE
"Feature" request: a changelog

### ISSUE THREAD

**Issue by dstj** [GaProgMan/OwaspHeaders.Core#46]
Hi,

Could you add a `changelog.md` file to explain features/fixes for each new version?

I've seen that the NuGet package has been updated (several times) about 6 days ago, yet I do not see any description (other than the commits themselves) explaining what those versions contain and if any breaking changes, security fixes, etc have been introduced.

Also, the [GitHub release page](https://github.com/GaProgMan/OwaspHeaders.Core/releases) contains only one version while the [NuGet](https://www.nuget.org/packages/OwaspHeaders.Core) contains about 20. Any reason for that discrepancy? 

Thanks!

**Comment by GaProgMan** [comment]
Good point. I've been quite lax with this. I'll go back through the previous releases and will create a change log for all of the previous releases.
I decided against using the releases page, since I'd automated the release for NuGet. But if there's enough demand for it, I'll start using it again.

**Comment by GaProgMan** [comment]
I've started work on this in the [feature/adding-changelog](https://github.com/GaProgMan/OwaspHeaders.Core/tree/feature/adding-changelog) branch.
