### ISSUE TITLE
Unit tests disabled if something is wrong in setup

### ISSUE THREAD

**Issue by Compufreak345** [GaProgMan/OwaspHeaders.Core#48]
The unit tests don't actually run if there is an error in the setup phase or the parts executing this. I think the "if"-clauses in the tests should be assertions instead. I also found one test where this caused the test to not do anything at all as there was passed a HeaderPresentConfig in a HeaderNotPresent-Test:

```
[Fact]
        public async Task Invoke_ExpectCtHeaderName_HeaderIsNotPresent()
        {
            // arrange
            var headerPresentConfig = SecureHeadersMiddlewareBuilder.CreateBuilder()
                .UseExpectCt("https://test.com/report").Build();
            var secureHeadersMiddleware = new SecureHeadersMiddleware(_onNext, headerPresentConfig);

            // act
            await secureHeadersMiddleware.Invoke(_context);

            // assert
            if (!headerPresentConfig.UseExpectCt)
            {
                Assert.False(_context.Response.Headers.ContainsKey(Constants.ExpectCtHeaderName));
            }
        }
```

I did change all tests to assert instead of not run if they are set up wrong. PR is coming right after this issue.

**Comment by GaProgMan** [comment]
Thank you for this. I had forgotten to say at the time that I merged your changes in.
