### ISSUE TITLE
SetCspUris with each of one CspCommandType.Directive and CspCommandType.Uri results in duplicate values in header

### ISSUE THREAD

**Issue by spasecookee** [GaProgMan/OwaspHeaders.Core#61]
Example, Startup.cs:
`                .UseContentSecurityPolicy()
.SetCspUris(new List<ContentSecurityPolicyElement>{
                    new ContentSecurityPolicyElement() {
                    CommandType = CspCommandType.Directive, DirectiveOrUri = "self"
                }, new ContentSecurityPolicyElement()
                    {
                        CommandType = CspCommandType.Uri,
                        DirectiveOrUri = "cdnjs.cloudflare.com"
                    }
                }, CspUriType.Style)`

In StringBuilderExtensions.BuildValuesForDirective, the second if statement (direvtiveValues.Any(), line 67) re-adds any Uri directives, so that cdnjs.cloudflare.com shows up twice in the policy. Probably don't need the two ifs (lines 48/67), and can just use the two wheres (lines 51/52 and 56/61)

**Comment by jamie-taylor-rjj** [comment]
This is fixed using [PR #66](https://github.com/GaProgMan/OwaspHeaders.Core/pull/66)
